const BalanceConstant = {
  BALANCE_DEDUCTING: 'BALANCE_DEDUCTING',
  BALANCE_DEDUCTED: 'BALANCE_DEDUCTED',
  BALANCE_FAILED_DEDUCTED: 'BALANCE_FAILED_DEDUCTED',
  BALANCE_INCREASED: 'BALANCE_INCREASED',
  BALANCE_FAILED_INCREASED: 'BALANCE_FAILED_INCREASED',
  BALANCE_RESET: 'BALANCE_RESET'
}

export default BalanceConstant;
